### ISSUE TITLE
readme instructions on how to build no longer work (setup.py)

### ISSUE THREAD

**Issue by rofl0r** [rainwoodman/tinypy#9]
```
$ python setup.py linux pygame
Traceback (most recent call last):
  File "setup.py", line 475, in <module>
    main()
  File "setup.py", line 16, in main
    chksize()
  File "setup.py", line 432, in chksize
    f = open(fname,'r'); t1 += len(f.read()); f.close()
IOError: [Errno 2] No such file or directory: '/home/user/tmp/tinypy/tinypy/tokenize.py'
```

i tried to fix it via this patch

```diff
diff --git a/setup.py b/setup.py
index 9b8f625..29ad36a 100644
--- a/setup.py
+++ b/setup.py
@@ -424,7 +424,8 @@ def shrink(fname):
 def chksize():
     t1,t2 = 0,0
     for fname in [
-        'tokenize.py','parse.py','encode.py','py2bc.py',
+        'compiler/tokenize.py','compiler/parse.py','compiler/encode.py',
+        'compiler/py2bc.py',
         'tp.h','list.c','dict.c','misc.c','string.c','builtins.c',
         'gc.c','ops.c','vm.c','tp.c','tpmain.c',
         ]:
```
however list.c isn't here anymore.

what's the current method to build it?

**Comment by rainwoodman** [comment]
I think it uses make instead of setup.py.

In this repo I gave up most of the plugin modules.
I haven't touched the code for a while, and apparently it was not building with Py3.

I pushed a commit to get it building, but it crashes running tpy tests/test_str.py with no error messages. I

Probably because I was in the middle of catching a gc error. The gc error I believe was fixed in tinypy++, but I don't exactly recall how -- there were loads of code reformatting in tinypy++ that I was having a hard time isolating fixes. I'll take a closer look tonight.

**Comment by rainwoodman** [comment]
There was a broken commit, and I reverted it in 408082fa2438257d3455e30f2fba05b4fead3126.

I also throw in a few improvements here and there in the follow up commits. Now

```
make
make test
```
should produce some sensible outputs. The test suite is very sparse though.

**Comment by rainwoodman** [comment]
Marking this fixed as the README has been updated for this fork of tinypy.
